import "@/styles/globals.css";

import { NavBar } from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/side-bar";
import { SessionProvider } from "next-auth/react";
import { Toaster, toast } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Toaster richColors />
        <SessionProvider>
          <TooltipProvider>
            <ThemeProvider attribute="class" defaultTheme="dark">
              <main className="flex min-h-screen flex-col bg-background font-sans antialiased text-foreground">
                <NavBar />
                <div className="flex h-[calc(100vh-5rem)]">
                  <Sidebar />
                  <div className="overflow-auto h-full w-full">{children}</div>
                </div>
              </main>
            </ThemeProvider>
          </TooltipProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
